apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-ktor
  namespace: spike-ktor
  annotations:
    image.toolkit.fluxcd.io/automation: "glob:v*"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spike-ktor
  template:
    metadata:
      labels:
        app: spike-ktor
    spec:
      containers:
      - name: spike-ktor
        # this will be automatically updated by Flux v2 when a new image is pushed based on the image polic
        # the comment is like {"$imagepolicy": "namespace:imagepolicy-name"}
        image: ilkimo/spike-ktor:v0.2.2 # {"$imagepolicy": "spike-ktor:spike-ktor"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
