---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-ktor
  namespace: spike-ktor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spike-ktor
  template:
    metadata:
      labels:
        app: spike-ktor
      annotations:
        fluxcd.io/automated: "true"
        fluxcd.io/tag.spike-ktor: semver:v*
    spec:
      containers:
      - name: spike-ktor
        image: ilkimo/spike-ktor # {"$imagepolicy": "spike-ktor:spike-ktor"}
        env:
        - name: imageUpgrades
          valueFrom:
            fieldRef:
              fieldPath: 'metadata.annotations["image.toolkit.fluxcd.io/automation"]'
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
