---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: spike-ktor
  namespace: spike-ktor
spec:
  imageRepositoryRef:
    name: spike-ktor
  policy:
    semver:
      range: ">=v0.2.0 <v1.0.0"

