---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: spike-ktor
  namespace: spike-ktor
spec:
  interval: 5m0s
  image: ilkimo/spike-ktor
#  secretRef:
#    name: dockerhub-credentials

