apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spike-ktor
  namespace: spike-ktor
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-automation.yaml