apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spike-ktor
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - image-repository.yaml
  - image-policy.yaml