apiVersion: v1
kind: Service
metadata:
  name: prove-semantic-release-service
  namespace: prove-semantic-release
  labels:
    app: prove-semantic-release
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: prove-semantic-release
