apiVersion: apps/v1
kind: Deployment
metadata:
  name: prove-semantic-release
  namespace: prove-semantic-release
  labels:
    app: prove-semantic-release
  annotations:
    image.toolkit.fluxcd.io/automation: "glob:v*-main"
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: prove-semantic-release
  template:
    metadata:
      labels:
        app: prove-semantic-release
    spec:
      containers:
        - name: api
          # this will be automatically updated by Flux v2 when a new image is pushed based on the image polic
          # the comment is like {"$imagepolicy": "namespace:imagepolicy-name"}
          image: gitlab.di.unito.it:5000/firstlife/oci/prove-semantic-release:v1.1.1-main # {"$imagepolicy": "prove-semantic-release:prove-semantic-release"}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "40m"
              memory: "200Mi"
            limits:
              cpu: "80m"
              memory: "400Mi"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: prove-semantic-release-secret
